name: Build h2 database tool
run-name: ${{ github.actor }} running actions
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup JDK 21 for x64
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'

      - name: Setup Grade
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          path: app/build/distributions
          name: 'H2 Tool Java Apps'
          retention-days: 5
          overwrite: 'false'

  mac-mative-exe:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest,windows-latest,ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup GraalVM
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build exe
        run: ./gradlew nativeCompile
      - name: archive executable
        run: ./gradlew nativeCompile
      - name: Archive artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          path: app/build/native/nativeCompile/
          name: h2-exe-${{ matrix.os }}




